### ISSUE TITLE
conflict with jupyter-notebook

### ISSUE THREAD

**Issue by phsamuel** [kirbyju/TCIA_Notebooks#25]
Hi,

I'm using Ubuntu 20.04 and is new to TCIA. I created a fresh environment and installed nothing except jupyter notebook. I use the command 

> pip install notebook

to install jupyter notebook.

But I have a conflict when trying to install tcia-utils. I got

> ERROR: jupyterlab-server 2.25.2 has requirement jsonschema>=4.18.0, but you'll have jsonschema 3.2.0 which is incompatible.
> ERROR: jupyter-events 0.9.0 has requirement jsonschema[format-nongpl]>=4.18.0, but you'll have jsonschema 3.2.0 which is incompatible.

What version of jupyter-notebook is supported?

Thanks!

**Comment by kirbyju** [comment]
I'm running 6.4.12 locally.  It also seems to work fine on 6.5.5.

**Comment by kirbyju** [comment]
I'm going to close this out since I haven't heard back.  Feel free to let me know if you're still having trouble after trying those versions.
