### ISSUE TITLE
TCIA Aspera CLI: Server aborted session

### ISSUE THREAD

**Issue by kathrinkhadra** [kirbyju/TCIA_Notebooks#34]
Hi everyone,

we are trying to download a pathology dataset (DLBCL-Morphology_v1) using the [`TCIA_Aspera_CLI_Downloads.ipynb`](https://github.com/kirbyju/TCIA_Notebooks/blob/main/TCIA_Aspera_CLI_Downloads.ipynb). We can download and install all of the packages but **when running cell 2 for the Biobank_CMB-GEC_v1 as a test:**

`!ascli faspex5 packages receive --url='https://faspex.cancerimagingarchive.net/aspera/faspex/public/package?context=eyJyZXNvdXJjZSI6InBhY2thZ2VzIiwidHlwZSI6ImV4dGVybmFsX2Rvd25sb2FkX3BhY2thZ2UiLCJpZCI6Ijc2MiIsInBhc3Njb2RlIjoiZDg0NmZlM2Q5ZjZjNzliYjUxYWU2MWMzNjJkNmE1ODJmMTc0YmVkYSIsInBhY2thZ2VfaWQiOiI3NjIiLCJlbWFpbCI6ImhlbHBAY2FuY2VyaW1hZ2luZ2FyY2hpdmUubmV0In0='`

**We encounter the following error:**

![image (16)](https://github.com/user-attachments/assets/2af03f80-89d1-4724-b9f0-ba544ee5c900)

**We tried it with different datasets and always got the same error.** We also got it for the normal GUI and app they recommend you install on TCIA. Are we doing something wrong? Should we log in somewhere? Thank you for your help.

**Comment by kirbyju** [comment]
Thanks for the heads up.  I can confirm the same behavior on my end, so I think we've got some ongoing server issues rather than any sort of issue with the notebook.  I've notified our sysadmins and will let you know when things are working again.

**Comment by kirbyju** [comment]
Please try again and let me know if you still have issues.

**Comment by kathrinkhadra** [comment]
Now it work, thank you so much for the useful repo and resolving this so fast.

**Comment by kathrinkhadra** [comment]
Now it work, thank you so much for the useful repo and resolving this so fast.
